MAP_WIDTH = 1080
MAP_HEIGHT = 800

CAR_LENGTH = 50
CAR_WIDTH = 25
WHEEL_LENGTH = 15
WHEEL_WIDTH = 7
START_POSITION_CAR = (CAR_WIDTH + WHEEL_WIDTH, MAP_HEIGHT - CAR_LENGTH - WHEEL_LENGTH)

GRADIENT_RESISTANCE_FILL = True

FPS = 60
FRAME_TIME = 1000. / FPS
